#!/usr/bin/perl
#
# install script for UNIXhelp 1.3

$old_scripturl = "http://unixhelp.ed.ac.uk/CGI";


## pageupdate (directory, file)
## 
## Updates a specific file according to the desired parameters

sub pageupdate {
  local($dir,$page) = @_;
  &replace($dir,$page,$old_scripturl,$script_dir);  # update scriptname
  if ($anonymous == 0) {                            # add maintainer
    &replace($dir,$page,"<!--MAINTNAME-->",$extra_footer);
  }
}


## input_details
##
## obtains references for custom install

sub input_details {
  print "스크립트 파일이 있는 디렉토리의 URL?\n";
  &getinput;
  $script_dir = $answer;
  print "\nUNIXhelp 문서를 관리할 사람의 email 주소?\n";
  print "이것은 각 페이지의 맨 끝에 추가된다.\n";
  print "필요없다면 그냥 Enter를 친다.\n";
  &getinput;
  $maint_name = $answer;
}

## these_are_ok
##
## checks with installer that parameters are correct

sub these_are_ok {
  print "\n\n스크립트 디렉토리가 있는 곳:\n";
  print "$script_dir\n";
  $anonymous = 0;
  print "\nUNIXhelp 관리자:\n";
  if (length($maint_name) == 0) {
    print "(익명)\n"; 
    $anonymous = 1;
  } else {
    print "$maint_name\n";
    $extra_footer=<<EOFOOT;
 제안이나 건의 사항은 
<A HREF="mailto:$maint_name">$maint_name</A>에게
EOFOOT
  }
  print "\n정확합니까 (y/n)? ";
  &getinput;
  print "\n";
  $answer =~ /[yY]/;
}

## getinput
##
## reads a value from stdin

sub getinput {
  $answer = <STDIN>;
  chop($answer);
}

## replace (directory, file, searchstring, replacestring)
## 
## does the search and replace operation on an individual file

sub replace {
  local($dir,$file,$sstring,$rstring) = @_;
  $remember = $/;                       # Note current record separator
  $/ = undef;                           # Ignore newline characters
  open(FILE,"$dir/$file") || die "Can't open file: $!\n";
                                        # open file if possible
  $_ = <FILE>;                          # Load entire file into matchspace
  s/$sstring/$rstring/gi;
  close(FILE);
  open(WRITEFILE,"> $dir/$file");
  print WRITEFILE $_;
  $/ = $remember;                       # Recognise separator again
  close(WRITEFILE);
}

## main
##
##

# check working directory
if (!(-d "Pages") || !(-d "Scripts")) {
  die "Working directory must be original location of install script\n"; }

# get necessary information from installer
do {&input_details} until &these_are_ok;
if (substr($script_dir,-1) eq "/") {
  chop($script_dir); }                # Remove trailing / if present

# update pages to conform
open(PAGES,"find Pages -type f -print |");             # Start page listing
while ($item = <PAGES>) {             # get next page if possible
  chop($item);                        # strip newline from page name
  &pageupdate(".",$item);
  print "Updated page: $item\n";
  }
close(PAGES);

# update search script
$extra_footer =~ s/@/\\@/g;
&pageupdate("Scripts","unixhelp_search");
print "Updated search script\n";
&pageupdate("Scripts","man-cgi");
print "Updated man-cgi script\n\n";

# end
print "** 모든 작업이 성공적으로 끝났습니다 **\n";
print "man-cgi 스크립트의 변수부분들을 적당하게 수정하십시오.\n";

